name: sorter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pip
  - numpy
  - opencv
  - py-opencv
  - pip:
    - snakeviz
    - matplotlib
    - pillow
    - scipy
    - chime
    - tensorflow
    - jinja2
    - flask
    - flask_cors
    - tqdm
    - plotext
    - scikeras
    - pySerial
    - readchar
    - pre-commit
