name: sorter311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - opencv
  - py-opencv
  - pip:
    - snakeviz
    - matplotlib
    - pillow
    - scipy
    - chime
    - jinja2
    - flask
    - flask_cors
    - tqdm
    - plotext
    - scikeras
    - pySerial
    - readchar
    - playsound
    - pre-commit
    - black
    - isort
    - pre-commit
    - tensorflow==2.17
