site_name: BrickSortingMachine
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage_guide.md
  - Architecture: architecture.md
  - MQTT Transition: MQTT.md

#theme: readthedocs  # not supporting the privacy plugin
theme:
  name: material

# The directory containing your Markdown source files.
docs_dir: doc

repo_url: https://github.com/your-username/your-repository

plugins:
  - search
  - mermaid2
  - privacy
