site_name: BrickSortingMachine
nav:
  - Home: index.md
  - About: about.md
theme: readthedocs

# The directory containing your Markdown source files.
docs_dir: doc

repo_url: https://github.com/your-username/your-repository
