name: Unit Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'false'
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Download test data
      run: |
        python tools/download_unpack_test_data.py
    - name: Install dependencies
      run: |
        conda env update --file environment311_linux_unittest.yml --name base
    - name: Lint with flake8
      run: |
        # uses .flake8 config
        flake8 . --count --show-source --statistics
    - name: Test with unittest
      run: |
        python -m unittest discover -s ./test  -p 'test_*.py' --failfast --buffer
